name: Flutter CI

# This workflow is triggered on pull requests to the repository.
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Init actions
      - name: Init Actions
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Restore packages
        run: flutter pub get

      # Statically analyze the Dart code for any errors.
      - name: Flutter Analyze
        run: flutter analyze .

      # Run tests for flutter project
      - name: Flutter Test
        run: flutter test
